version: '3.8'

services:
  frontend:
    build:
      context: ./real-estate-search
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Ensure this matches the port your frontend server listens on
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    build:
      context: ./RealEstateSearchService
      dockerfile: Dockerfile
    ports:
      - "8000:80"  # Ensure this matches the port your backend server listens on
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "Elasticsearch:Uri=http://elasticsearch:9200"
      - "Elasticsearch:DefaultIndex=real-estate-listings"
      - "ConnectionStrings:DefaultConnection=Host=db;Database=realestatedb;Username=koray;Password=avwefaw45qer2q34253..8319264"
    depends_on:
      - elasticsearch
      - db
    networks:
      - mynetwork

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - mynetwork

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: koray
      POSTGRES_PASSWORD: avwefaw45qer2q34253..8319264
      POSTGRES_DB: realestatedb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  esdata1:
    driver: local
  postgres-data:
    driver: local

networks:
  mynetwork:
    driver: bridge  
